Script started on Wed 28 Feb 2024 05:46:23 AM PST
]0;ndukwec@crystalcove:~/hw4[ndukwec@crystalcove ~/hw4]$ make
gcc -ansi -std=c11 -Wall -c PhotoLab.c -o PhotoLab.o
gcc -ansi -std=c11 -Wall -lm PhotoLab.o FileIO.o Test.o Image.o -L. -lFilter -o PhotoLab
gcc -ansi -std=c11 -Wall -c -DDEBUG -g -c PhotoLab.c -o PhotoLabTest.o
gcc -ansi -std=c11 -Wall -lm PhotoLabTest.o FileIO.o Image.o Test_DEBUG.o -L. -lFilter -o PhotoLabTest
]0;ndukwec@crystalcove:~/hw4[ndukwec@crystalcove ~/hw4]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image horizontally
10: Add border to an image
11: Create a fisheye image
12: Posterize an image
13: Rotate and zoom an image
14: Add Motion Blur to an image
15: Crop an image
16: Resize an image
17: Add Watermark to an image
18: Rotate an image by 90 degrees
19: Test all functions
20: Exit
Please make your choice: 19
0 mismatching pixels (0.000%) identified in bw_diff.ppm.
0 mismatching pixels (0.000%) identified in negative_diff.ppm.
0 mismatching pixels (0.000%) identified in colorfilter_diff.ppm.
0 mismatching pixels (0.000%) identified in edge_diff.ppm.
0 mismatching pixels (0.000%) identified in shuffle_diff.ppm.
0 mismatching pixels (0.000%) identified in vflip_diff.ppm.
0 mismatching pixels (0.000%) identified in hmirror_diff.ppm.
0 mismatching pixels (0.000%) identified in border_diff.ppm.
0 mismatching pixels (0.000%) identified in fisheye_diff.ppm.
0 mismatching pixels (0.000%) identified in rotate_diff.ppm.
0 mismatching pixels (0.000%) identified in posterize_diff.ppm.
0 mismatching pixels (0.000%) identified in blur_diff.ppm.
0 mismatching pixels (0.000%) identified in crop_diff.ppm.
0 mismatching pixels (0.000%) identified in smallresize_diff.ppm.
0 mismatching pixels (0.000%) identified in bigresize_diff.ppm.
0 mismatching pixels (0.000%) identified in watermark_diff.ppm.
0 mismatching pixels (0.000%) identified in rotateby90_diff.ppm.
AutoTest finished successfully.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image horizontally
10: Add border to an image
11: Create a fisheye image
12: Posterize an image
13: Rotate and zoom an image
14: Add Motion Blur to an image
15: Crop an image
16: Resize an image
17: Add Watermark to an image
18: Rotate an image by 90 degrees
19: Test all functions
20: Exit
Please make your choice: 20
You exit the program.
]0;ndukwec@crystalcove:~/hw4[ndukwec@crystalcove ~/hw4]$ valgrind --leak-check=full PhotoLabTest
valgrind: PhotoLabTest: command not found
]0;ndukwec@crystalcove:~/hw4[ndukwec@crystalcove ~/hw4]$ valgrind --leak-check=full PhotoLabTest[1@.[1@/
==44403== Memcheck, a memory error detector
==44403== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==44403== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==44403== Command: ./PhotoLabTest
==44403== 
0 mismatching pixels (0.000%) identified in bw_diff.ppm.
Black and White tested!

0 mismatching pixels (0.000%) identified in negative_diff.ppm.
Negative tested!

0 mismatching pixels (0.000%) identified in colorfilter_diff.ppm.
Color Filter tested!

0 mismatching pixels (0.000%) identified in edge_diff.ppm.
Edge Detection tested!

0 mismatching pixels (0.000%) identified in shuffle_diff.ppm.
Shuffle tested!

0 mismatching pixels (0.000%) identified in vflip_diff.ppm.
VFlip tested!

0 mismatching pixels (0.000%) identified in hmirror_diff.ppm.
HMirror tested!

0 mismatching pixels (0.000%) identified in border_diff.ppm.
Add Border tested!

0 mismatching pixels (0.000%) identified in fisheye_diff.ppm.
Fisheye tested!

0 mismatching pixels (0.000%) identified in rotate_diff.ppm.
Rotate tested!

0 mismatching pixels (0.000%) identified in posterize_diff.ppm.
Posterize tested!

0 mismatching pixels (0.000%) identified in blur_diff.ppm.
MotionBlur tested!

0 mismatching pixels (0.000%) identified in crop_diff.ppm.
Crop tested!

0 mismatching pixels (0.000%) identified in smallresize_diff.ppm.
0 mismatching pixels (0.000%) identified in bigresize_diff.ppm.
Resize tested!

0 mismatching pixels (0.000%) identified in watermark_diff.ppm.
Watermark tested!

0 mismatching pixels (0.000%) identified in rotateby90_diff.ppm.
RotateBy90 tested!

==44403== 
==44403== HEAP SUMMARY:
==44403==     in use at exit: 0 bytes in 0 blocks
==44403==   total heap usage: 139 allocs, 139 frees, 11,030,016 bytes allocated
==44403== 
==44403== All heap blocks were freed -- no leaks are possible
==44403== 
==44403== For lists of detected and suppressed errors, rerun with: -s
==44403== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;ndukwec@crystalcove:~/hw4[ndukwec@crystalcove ~/hw4]$ make clean
rm -f *.o
rm -f PhotoLab
rm -f PhotoLabTest
rm -f bigresize.ppm smallresize.ppm blur.ppm border.ppm colorfilter.ppm bw.ppm crop.ppm edge.ppm fisheye.ppm hmirror.ppm posterize.ppm negative.ppm rotate.ppm shuffle.ppm vflip.ppm
]0;ndukwec@crystalcove:~/hw4[ndukwec@crystalcove ~/hw4]$ exit
exit

Script done on Wed 28 Feb 2024 05:48:31 AM PST
